return function()
  local normal = astronvim.get_hlgroup "Normal"
  local fg, bg = normal.fg, normal.bg
  local bg_alt = astronvim.get_hlgroup("Visual").bg
  local green = astronvim.get_hlgroup("String").fg
  local red = astronvim.get_hlgroup("Error").fg

  return {
    TelescopeBorder = { fg = bg_alt, bg = bg },
    TelescopeNormal = { bg = bg },
    TelescopePreviewBorder = { fg = bg, bg = bg },
    TelescopePreviewNormal = { bg = bg },
    TelescopePreviewTitle = { fg = bg, bg = green },
    TelescopePromptBorder = { fg = bg_alt, bg = bg_alt },
    TelescopePromptNormal = { fg = fg, bg = bg_alt },
    TelescopePromptPrefix = { fg = red, bg = bg_alt },
    TelescopePromptTitle = { fg = bg, bg = red },
    TelescopeResultsBorder = { fg = bg, bg = bg },
    TelescopeResultsNormal = { bg = bg },
    TelescopeResultsTitle = { fg = bg, bg = bg },
    --
    --VS code cmp
    CmpItemKindConstructor = { fg = "#f28b25" },
    CmpItemKindUnit = { fg = "#D4D4D4" },
    CmpItemKindProperty = { fg = "#D4D4D4" },
    CmpItemKindKeyword = { fg = "#D4D4D4" },
    CmpItemKindMethod = { fg = "#C586C0" },
    CmpItemKindFunction = { fg = "#C586C0" },
    CmpItemKindColor = { fg = "#C586C0" },
    CmpItemKindText = { fg = "#9CDCFE" },
    CmpItemKindInterface = { fg = "#9CDCFE" },
    CmpItemKindVariable = { fg = "#9CDCFE" },
    CmpItemKindField = { fg = "#9CDCFE" },
    CmpItemKindValue = { fg = "#9CDCFE" },
    CmpItemKindEnum = { fg = "#9CDCFE" },
    CmpItemKindEnumMember = { fg = "#9CDCFE" },
    CmpItemKindStruct = { fg = "#9CDCFE" },
    CmpItemKindReference = { fg = "#9CDCFE" },
    CmpItemKindTypeParameter = { fg = "#9CDCFE" },
    CmpItemKindSnippet = { fg = "#D4D4D4" },
    CmpItemKindClass = { fg = "#f28b25" },
    CmpItemKindModule = { fg = "#D4D4D4" },
    CmpItemKindOperator = { fg = "#D4D4D4" },
    CmpItemKindConstant = { fg = "#D4D4D4" },
    CmpItemKindFile = { fg = "#D4D4D4" },
    CmpItemKindFolder = { fg = "#D4D4D4" },
    CmpItemKindEvent = { fg = "#D4D4D4" },
    CmpItemAbbrMatch = { fg = "#18a2fe", bold = true },
    CmpItemAbbrMatchFuzzy = { fg = "#18a2fe", bold = true },
    CmpItemMenu = { fg = "#777d86" },
    -- VS code tree
    AerialArrayIcon = { fg = "" },
    AerialClassIcon = { fg = "#f28b25" },
    AerialConstantIcon = { fg = "#D4D4D4" },
    AerialConstructorIcon = { fg = "#f28b25" },
    AerialEnumIcon = { fg = "#9CDCFE" },
    AeiralEnumMember = { fg = "#9CDCFE" },
    AerialEventIcon = { fg = "#D4D4D4" },
    AerialFieldIcon = { fg = "#9CDCFE" },
    AerialFileIcon = { fg = "#D4D4D4" },
    AerialFunctionIcon = { fg = "#C586C0" },
    AerialInterfaceIcon = { fg = "#9CDCFE" },
    AerialKeyIcon = { fg = "#D4D4D4" },
    AerialMethodIcon = { fg = "#C586C0" },
    AerialModuleIcon = { fg = "#D4D4D4" },
    AerialNamespaceIcon = { fg = "#D4D4D4" },
    AerialNullIcon = { fg = "#D4D4D4" },
    AerialNumberIcon = { fg = "#D4D4D4" },
    AerialObjectIcon = { fg = "#f28b25" },
    AerialOperatorIcon = { fg = "#D4D4D4" },
    AerialPackageIcon = { fg = "#D4D4D4" },
    AerialPropertyIcon = { fg = "#D4D4D4" },
    AerialStringIcon = { fg = "#9CDCFE" },
    AerialStructIcon = { fg = "#f28b25" },
    AerialTypeParameter = { fg = "#9CDCFE" },
    AerialVariableIcon = { fg = "#9CDCFE" },
  }
end
