return {
	{
		"onsails/lspkind.nvim",
		opts = {
			mode = "symbol_text",
			preset = "codicons",
			menu = {
				nvim_lua = "[NeoVim]",
				nvim_lsp = "[LSP]",
				luasnip = "[LuaSnip]",
				neorg = "[Neorg]",
				npm = "[NPM]",
				buffer = "[Buffer]",
				path = "[Path]",
			},
			symbol_map = {
				Array = "",
				Boolean = "",
				Key = "",
				Namespace = "",
				Null = "",
				Number = "",
				Object = "",
				Package = "",
				String = "",
				Text = " ",
				Method = " ",
				Function = " ",
				Constructor = " ",
				Field = " ",
				Variable = " ",
				Class = " ",
				Interface = " ",
				Module = " ",
				Property = " ",
				Unit = " ",
				Value = " ",
				Enum = " ",
				Keyword = " ",
				Snippet = " ",
				Color = " ",
				File = " ",
				Reference = " ",
				Folder = " ",
				EnumMember = " ",
				Constant = " ",
				Struct = " ",
				Event = " ",
				Operator = " ",
				TypeParameter = " ",
			},
		},
	},
}
