return function(config)
  config.preset = "codicons"
  config.symbol_map = {
    Array = "",
    Boolean = "",
    Key = "",
    Namespace = "",
    Null = "",
    Number = "",
    Object = "",
    Package = "",
    String = "",
    Text = " ",
    Method = " ",
    Function = " ",
    Constructor = " ",
    Field = " ",
    Variable = " ",
    Class = " ",
    Interface = " ",
    Module = " ",
    Property = " ",
    Unit = " ",
    Value = " ",
    Enum = " ",
    Keyword = " ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Reference = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  }
  return config
end
