name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
# branches:
#   - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Cargo Binaries
        id: deps-cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-lint-${{ hashFiles('.github/workflows/ci.yml') }}

      - name: Install Selene
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: cargo install selene

      - name: Lint
        run: make lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Cargo Binaries
        id: deps-cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-format-${{ hashFiles('.github/workflows/ci.yml') }}

      - name: Install Stylua
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: cargo install stylua

      - name: Check format
        id: check-format
        run: stylua --check .

      - name: Format
        # if: steps.check-format.conclusion == 'failure'
        run: echo "conclusion: ${{ steps.check-format.conclusion }}"

      # - name: Commit changes
      #   if: steps.check-format.conclusion == 'failure'
      #   run: |
      #     git config --global user.name 'Github Actions'
      #     git config --global user.email 'snikoletopulos@users.noreply.github.com'
      #     git commit -am "Format code"
      #     git push
