name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
# branches:
#   - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion: ["5.1", "5.4"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Selene
        run: cargo install selene

      - name: Lint
        run: make lint

      # - uses: leafo/gh-actions-lua@v5
      #   with:
      #     luaVersion: ${{ matrix.luaVersion }}

  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        luaVersion: ["5.1", "5.4"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Stylua
        run: cargo install stylua

      - name: Format
        run: make lint

      # - uses: leafo/gh-actions-lua@v5
      #   with:
      #     luaVersion: ${{ matrix.luaVersion }}
      # - uses: JohnnyMorganz/stylua-action@v4
