name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
# branches:
#   - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Cargo Binaries
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-lint-${{ hashFiles('.github/workflows/cargo.yml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-lint-

      - name: Install Selene
        run: cargo install selene

      - name: Lint
        run: make lint

      # - uses: leafo/gh-actions-lua@v5
      #   with:
      #     luaVersion: ${{ matrix.luaVersion }}

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Cargo Binaries
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-format-${{ hashFiles('.github/workflows/cargo.yml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-format-

      - name: Install Stylua
        run: cargo install stylua

      - name: Format
        run: make lint

      # - uses: leafo/gh-actions-lua@v5
      #   with:
      #     luaVersion: ${{ matrix.luaVersion }}
      # - uses: JohnnyMorganz/stylua-action@v4
